# Generated by Django 4.2.7 on 2023-11-17 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_series_remove_post_series_alter_post_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Book Title", max_length=200, unique=True),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_on"],},
        ),
        migrations.AlterModelOptions(name="series", options={},),
        migrations.RemoveField(model_name="series", name="author",),
        migrations.RemoveField(model_name="series", name="created_on",),
        migrations.RemoveField(model_name="series", name="posts",),
        migrations.RemoveField(model_name="series", name="title",),
        migrations.AddField(
            model_name="series",
            name="series",
            field=models.CharField(default="Series Title", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="slug",
            field=models.SlugField(default="series-title", max_length=200, unique=True),
        ),
        migrations.DeleteModel(name="Translations",),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="translations.series"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="translations.book",
            ),
        ),
    ]
