# Generated by Django 4.2.7 on 2023-11-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "translations",
            "0003_book_alter_series_options_remove_series_author_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(default="Book Title", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="series",
            field=models.CharField(default="Series Title", max_length=100, unique=True),
        ),
    ]
