# Generated by Django 4.2.7 on 2023-11-17 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_alter_book_title_alter_post_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="series", name="series",),
        migrations.AddField(
            model_name="series",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="series",
            name="title",
            field=models.CharField(default="Series Title", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(default="Book Title", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
