# Generated by Django 4.2.7 on 2023-11-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "translations",
            "0005_remove_series_series_series_created_on_series_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="series", name="created_on",),
    ]
