# Generated by Django 4.2.7 on 2023-11-17 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0006_remove_series_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
