# Generated by Django 4.2.7 on 2023-11-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0009_series_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="web_novel",
            field=models.BooleanField(default=False),
        ),
    ]
