# Generated by Django 4.2.7 on 2023-11-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0010_series_web_novel"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="book", new_name="book_id",),
    ]
