# Generated by Django 4.2.7 on 2023-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0011_rename_book_post_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="web_novel",
            field=models.IntegerField(
                choices=[(0, "Web Novel"), (1, "Light Novel")], default=1
            ),
        ),
    ]
