# Generated by Django 4.2.7 on 2023-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0012_alter_series_web_novel"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
