# Generated by Django 4.2.7 on 2023-11-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0013_series_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="slug", new_name="book_slug",
        ),
    ]
