# Generated by Django 4.2.7 on 2023-11-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0014_rename_slug_book_book_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="slug", new_name="post_slug",
        ),
        migrations.RenameField(
            model_name="series", old_name="slug", new_name="series_slug",
        ),
    ]
